//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.17929
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBusNoti.BusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.api.javaweb/", ConfigurationName="BusService.BusLocationInterface")]
    public interface BusLocationInterface {
        
        // CODEGEN: 매개 변수 모드를 사용하여 캡처할 수 없는 추가 스키마 정보가 'return' 매개 변수에 필요합니다. 특정 특성은 'System.Xml.Serialization.XmlElementAttribute'입니다.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(apiResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CBusNoti.BusService.getBusLocationListResponse getBusLocationList(CBusNoti.BusService.getBusLocationList request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.api.javaweb/")]
    public partial class busLocationListResponse : apiResponse {
        
        private busLocation[] msgBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("busLocationList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public busLocation[] msgBody {
            get {
                return this.msgBodyField;
            }
            set {
                this.msgBodyField = value;
                this.RaisePropertyChanged("msgBody");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.api.javaweb/")]
    public partial class busLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string endBusField;
        
        private string lowPlateField;
        
        private string plateNoField;
        
        private string routeIdField;
        
        private string stationIdField;
        
        private string stationSeqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string endBus {
            get {
                return this.endBusField;
            }
            set {
                this.endBusField = value;
                this.RaisePropertyChanged("endBus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lowPlate {
            get {
                return this.lowPlateField;
            }
            set {
                this.lowPlateField = value;
                this.RaisePropertyChanged("lowPlate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string plateNo {
            get {
                return this.plateNoField;
            }
            set {
                this.plateNoField = value;
                this.RaisePropertyChanged("plateNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string routeId {
            get {
                return this.routeIdField;
            }
            set {
                this.routeIdField = value;
                this.RaisePropertyChanged("routeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
                this.RaisePropertyChanged("stationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string stationSeq {
            get {
                return this.stationSeqField;
            }
            set {
                this.stationSeqField = value;
                this.RaisePropertyChanged("stationSeq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.api.javaweb/")]
    public partial class resMsgHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queryTimeField;
        
        private int resultCodeField;
        
        private string resultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string queryTime {
            get {
                return this.queryTimeField;
            }
            set {
                this.queryTimeField = value;
                this.RaisePropertyChanged("queryTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string resultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("resultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.api.javaweb/")]
    public partial class resComMsgHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errMsgField;
        
        private string requestMsgIDField;
        
        private string responseMsgIDField;
        
        private string responseTimeField;
        
        private string returnCodeField;
        
        private string successYNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestMsgID {
            get {
                return this.requestMsgIDField;
            }
            set {
                this.requestMsgIDField = value;
                this.RaisePropertyChanged("requestMsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string responseMsgID {
            get {
                return this.responseMsgIDField;
            }
            set {
                this.responseMsgIDField = value;
                this.RaisePropertyChanged("responseMsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string successYN {
            get {
                return this.successYNField;
            }
            set {
                this.successYNField = value;
                this.RaisePropertyChanged("successYN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(busLocationListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.api.javaweb/")]
    public partial class apiResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resComMsgHeader comMsgHeaderField;
        
        private resMsgHeader msgHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resComMsgHeader comMsgHeader {
            get {
                return this.comMsgHeaderField;
            }
            set {
                this.comMsgHeaderField = value;
                this.RaisePropertyChanged("comMsgHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public resMsgHeader msgHeader {
            get {
                return this.msgHeaderField;
            }
            set {
                this.msgHeaderField = value;
                this.RaisePropertyChanged("msgHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBusLocationList", WrapperNamespace="http://ws.api.javaweb/", IsWrapped=true)]
    public partial class getBusLocationList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.api.javaweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.api.javaweb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getBusLocationList() {
        }
        
        public getBusLocationList(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBusLocationListResponse", WrapperNamespace="http://ws.api.javaweb/", IsWrapped=true)]
    public partial class getBusLocationListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.api.javaweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CBusNoti.BusService.busLocationListResponse @return;
        
        public getBusLocationListResponse() {
        }
        
        public getBusLocationListResponse(CBusNoti.BusService.busLocationListResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusLocationInterfaceChannel : CBusNoti.BusService.BusLocationInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusLocationInterfaceClient : System.ServiceModel.ClientBase<CBusNoti.BusService.BusLocationInterface>, CBusNoti.BusService.BusLocationInterface {
        
        public BusLocationInterfaceClient() {
        }
        
        public BusLocationInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusLocationInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusLocationInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusLocationInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CBusNoti.BusService.getBusLocationListResponse CBusNoti.BusService.BusLocationInterface.getBusLocationList(CBusNoti.BusService.getBusLocationList request) {
            return base.Channel.getBusLocationList(request);
        }
        
        public CBusNoti.BusService.busLocationListResponse getBusLocationList(string arg0, string arg1) {
            CBusNoti.BusService.getBusLocationList inValue = new CBusNoti.BusService.getBusLocationList();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CBusNoti.BusService.getBusLocationListResponse retVal = ((CBusNoti.BusService.BusLocationInterface)(this)).getBusLocationList(inValue);
            return retVal.@return;
        }
    }
}
